language: python
python:
  - 2.6
  - 2.7
install:
  - apt-get install -yq2 --no-install-recommends dvipng graphviz imagemagick lilypond source-highlight texlive-latex-base
script:
  - time python tests/testasciidoc.py update
  - python asciidoc.py --doctest
  - python asciidocapi.py
  - time python tests/testasciidoc.py run
  - git clean -f tests/data
